name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.JENKINS_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts


    - name: Deploy using rsync
      run: |
        rsync -avz --exclude '.git' -e "ssh -o StrictHostKeyChecking=no" ./ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/webapp-test

    # - name: Restart Application on EC2
    #   run: |
    #     ssh ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
    #       cd /home/ubuntu/app
    #       source venv/bin/activate  # If using a virtual environment
    #       pip install -r requirements.txt
    #       systemctl restart your-app  # Restart the app if running as a service
    #     EOF
